// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package user

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *LoginReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_LoginReq[number], err)
}

func (x *LoginReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserAccount, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *LoginReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserPassword, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *LoginResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_LoginResp[number], err)
}

func (x *LoginResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadUint32(buf, _type)
	return offset, err
}

func (x *LoginResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserRole, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *RegisterReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_RegisterReq[number], err)
}

func (x *RegisterReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserAccount, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *RegisterReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserPassword, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *RegisterResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_RegisterResp[number], err)
}

func (x *RegisterResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadUint32(buf, _type)
	return offset, err
}

func (x *RegisterResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserRole, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdateReq[number], err)
}

func (x *UpdateReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *UpdateReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.UserAvatar, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.UserProfile, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateReq) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.UserRole, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
}

func (x *GetUserReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetUserReq[number], err)
}

func (x *GetUserReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GetUserResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 10:
		offset, err = x.fastReadField10(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 11:
		offset, err = x.fastReadField11(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetUserResp[number], err)
}

func (x *GetUserResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GetUserResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserAccount, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetUserResp) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.UserPassword, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetUserResp) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.UserName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetUserResp) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.UserAvatar, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetUserResp) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.UserProfile, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetUserResp) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.UserRole, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetUserResp) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	x.EditTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetUserResp) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	x.CreateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetUserResp) fastReadField10(buf []byte, _type int8) (offset int, err error) {
	x.UpdateTime, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetUserResp) fastReadField11(buf []byte, _type int8) (offset int, err error) {
	x.IsDelete, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *DeleteUserReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_DeleteUserReq[number], err)
}

func (x *DeleteUserReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *AddUserReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AddUserReq[number], err)
}

func (x *AddUserReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.UserAccount, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddUserReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.UserPassword, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddUserReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.UserName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddUserReq) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.UserAvatar, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddUserReq) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.UserProfile, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddUserReq) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	x.UserRole, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AddUserResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
}

func (x *DeleteUserResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
}

func (x *ListUserReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListUserReq[number], err)
}

func (x *ListUserReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.PageNum, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListUserReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.PageSize, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ListUserReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.UserName, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListUserReq) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Account, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListUserResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListUserResp[number], err)
}

func (x *ListUserResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v GetUserResp
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.UserList = append(x.UserList, &v)
	return offset, nil
}

func (x *ListUserResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Total, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *LoginReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *LoginReq) fastWriteField1(buf []byte) (offset int) {
	if x.UserAccount == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetUserAccount())
	return offset
}

func (x *LoginReq) fastWriteField2(buf []byte) (offset int) {
	if x.UserPassword == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetUserPassword())
	return offset
}

func (x *LoginResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *LoginResp) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteUint32(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *LoginResp) fastWriteField2(buf []byte) (offset int) {
	if x.UserRole == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetUserRole())
	return offset
}

func (x *RegisterReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *RegisterReq) fastWriteField1(buf []byte) (offset int) {
	if x.UserAccount == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetUserAccount())
	return offset
}

func (x *RegisterReq) fastWriteField2(buf []byte) (offset int) {
	if x.UserPassword == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetUserPassword())
	return offset
}

func (x *RegisterResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *RegisterResp) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteUint32(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *RegisterResp) fastWriteField2(buf []byte) (offset int) {
	if x.UserRole == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetUserRole())
	return offset
}

func (x *UpdateReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *UpdateReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *UpdateReq) fastWriteField2(buf []byte) (offset int) {
	if x.UserName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetUserName())
	return offset
}

func (x *UpdateReq) fastWriteField3(buf []byte) (offset int) {
	if x.UserAvatar == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetUserAvatar())
	return offset
}

func (x *UpdateReq) fastWriteField4(buf []byte) (offset int) {
	if x.UserProfile == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetUserProfile())
	return offset
}

func (x *UpdateReq) fastWriteField5(buf []byte) (offset int) {
	if x.UserRole == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetUserRole())
	return offset
}

func (x *UpdateResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	return offset
}

func (x *GetUserReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetUserReq) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *GetUserResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	offset += x.fastWriteField10(buf[offset:])
	offset += x.fastWriteField11(buf[offset:])
	return offset
}

func (x *GetUserResp) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetId())
	return offset
}

func (x *GetUserResp) fastWriteField2(buf []byte) (offset int) {
	if x.UserAccount == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetUserAccount())
	return offset
}

func (x *GetUserResp) fastWriteField3(buf []byte) (offset int) {
	if x.UserPassword == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetUserPassword())
	return offset
}

func (x *GetUserResp) fastWriteField4(buf []byte) (offset int) {
	if x.UserName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetUserName())
	return offset
}

func (x *GetUserResp) fastWriteField5(buf []byte) (offset int) {
	if x.UserAvatar == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetUserAvatar())
	return offset
}

func (x *GetUserResp) fastWriteField6(buf []byte) (offset int) {
	if x.UserProfile == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetUserProfile())
	return offset
}

func (x *GetUserResp) fastWriteField7(buf []byte) (offset int) {
	if x.UserRole == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 7, x.GetUserRole())
	return offset
}

func (x *GetUserResp) fastWriteField8(buf []byte) (offset int) {
	if x.EditTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 8, x.GetEditTime())
	return offset
}

func (x *GetUserResp) fastWriteField9(buf []byte) (offset int) {
	if x.CreateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 9, x.GetCreateTime())
	return offset
}

func (x *GetUserResp) fastWriteField10(buf []byte) (offset int) {
	if x.UpdateTime == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 10, x.GetUpdateTime())
	return offset
}

func (x *GetUserResp) fastWriteField11(buf []byte) (offset int) {
	if !x.IsDelete {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 11, x.GetIsDelete())
	return offset
}

func (x *DeleteUserReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *DeleteUserReq) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *AddUserReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	return offset
}

func (x *AddUserReq) fastWriteField2(buf []byte) (offset int) {
	if x.UserAccount == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetUserAccount())
	return offset
}

func (x *AddUserReq) fastWriteField3(buf []byte) (offset int) {
	if x.UserPassword == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetUserPassword())
	return offset
}

func (x *AddUserReq) fastWriteField4(buf []byte) (offset int) {
	if x.UserName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetUserName())
	return offset
}

func (x *AddUserReq) fastWriteField5(buf []byte) (offset int) {
	if x.UserAvatar == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetUserAvatar())
	return offset
}

func (x *AddUserReq) fastWriteField6(buf []byte) (offset int) {
	if x.UserProfile == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 6, x.GetUserProfile())
	return offset
}

func (x *AddUserReq) fastWriteField7(buf []byte) (offset int) {
	if x.UserRole == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 7, x.GetUserRole())
	return offset
}

func (x *AddUserResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	return offset
}

func (x *DeleteUserResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	return offset
}

func (x *ListUserReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *ListUserReq) fastWriteField1(buf []byte) (offset int) {
	if x.PageNum == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetPageNum())
	return offset
}

func (x *ListUserReq) fastWriteField2(buf []byte) (offset int) {
	if x.PageSize == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetPageSize())
	return offset
}

func (x *ListUserReq) fastWriteField3(buf []byte) (offset int) {
	if x.UserName == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetUserName())
	return offset
}

func (x *ListUserReq) fastWriteField4(buf []byte) (offset int) {
	if x.Account == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetAccount())
	return offset
}

func (x *ListUserResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *ListUserResp) fastWriteField1(buf []byte) (offset int) {
	if x.UserList == nil {
		return offset
	}
	for i := range x.GetUserList() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetUserList()[i])
	}
	return offset
}

func (x *ListUserResp) fastWriteField2(buf []byte) (offset int) {
	if x.Total == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetTotal())
	return offset
}

func (x *LoginReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *LoginReq) sizeField1() (n int) {
	if x.UserAccount == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetUserAccount())
	return n
}

func (x *LoginReq) sizeField2() (n int) {
	if x.UserPassword == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetUserPassword())
	return n
}

func (x *LoginResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *LoginResp) sizeField1() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeUint32(1, x.GetUserId())
	return n
}

func (x *LoginResp) sizeField2() (n int) {
	if x.UserRole == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetUserRole())
	return n
}

func (x *RegisterReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *RegisterReq) sizeField1() (n int) {
	if x.UserAccount == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetUserAccount())
	return n
}

func (x *RegisterReq) sizeField2() (n int) {
	if x.UserPassword == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetUserPassword())
	return n
}

func (x *RegisterResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *RegisterResp) sizeField1() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeUint32(1, x.GetUserId())
	return n
}

func (x *RegisterResp) sizeField2() (n int) {
	if x.UserRole == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetUserRole())
	return n
}

func (x *UpdateReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *UpdateReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *UpdateReq) sizeField2() (n int) {
	if x.UserName == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetUserName())
	return n
}

func (x *UpdateReq) sizeField3() (n int) {
	if x.UserAvatar == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetUserAvatar())
	return n
}

func (x *UpdateReq) sizeField4() (n int) {
	if x.UserProfile == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetUserProfile())
	return n
}

func (x *UpdateReq) sizeField5() (n int) {
	if x.UserRole == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetUserRole())
	return n
}

func (x *UpdateResp) Size() (n int) {
	if x == nil {
		return n
	}
	return n
}

func (x *GetUserReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetUserReq) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *GetUserResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	n += x.sizeField10()
	n += x.sizeField11()
	return n
}

func (x *GetUserResp) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetId())
	return n
}

func (x *GetUserResp) sizeField2() (n int) {
	if x.UserAccount == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetUserAccount())
	return n
}

func (x *GetUserResp) sizeField3() (n int) {
	if x.UserPassword == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetUserPassword())
	return n
}

func (x *GetUserResp) sizeField4() (n int) {
	if x.UserName == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetUserName())
	return n
}

func (x *GetUserResp) sizeField5() (n int) {
	if x.UserAvatar == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetUserAvatar())
	return n
}

func (x *GetUserResp) sizeField6() (n int) {
	if x.UserProfile == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetUserProfile())
	return n
}

func (x *GetUserResp) sizeField7() (n int) {
	if x.UserRole == "" {
		return n
	}
	n += fastpb.SizeString(7, x.GetUserRole())
	return n
}

func (x *GetUserResp) sizeField8() (n int) {
	if x.EditTime == "" {
		return n
	}
	n += fastpb.SizeString(8, x.GetEditTime())
	return n
}

func (x *GetUserResp) sizeField9() (n int) {
	if x.CreateTime == "" {
		return n
	}
	n += fastpb.SizeString(9, x.GetCreateTime())
	return n
}

func (x *GetUserResp) sizeField10() (n int) {
	if x.UpdateTime == "" {
		return n
	}
	n += fastpb.SizeString(10, x.GetUpdateTime())
	return n
}

func (x *GetUserResp) sizeField11() (n int) {
	if !x.IsDelete {
		return n
	}
	n += fastpb.SizeBool(11, x.GetIsDelete())
	return n
}

func (x *DeleteUserReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *DeleteUserReq) sizeField1() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetUserId())
	return n
}

func (x *AddUserReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	return n
}

func (x *AddUserReq) sizeField2() (n int) {
	if x.UserAccount == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetUserAccount())
	return n
}

func (x *AddUserReq) sizeField3() (n int) {
	if x.UserPassword == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetUserPassword())
	return n
}

func (x *AddUserReq) sizeField4() (n int) {
	if x.UserName == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetUserName())
	return n
}

func (x *AddUserReq) sizeField5() (n int) {
	if x.UserAvatar == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetUserAvatar())
	return n
}

func (x *AddUserReq) sizeField6() (n int) {
	if x.UserProfile == "" {
		return n
	}
	n += fastpb.SizeString(6, x.GetUserProfile())
	return n
}

func (x *AddUserReq) sizeField7() (n int) {
	if x.UserRole == "" {
		return n
	}
	n += fastpb.SizeString(7, x.GetUserRole())
	return n
}

func (x *AddUserResp) Size() (n int) {
	if x == nil {
		return n
	}
	return n
}

func (x *DeleteUserResp) Size() (n int) {
	if x == nil {
		return n
	}
	return n
}

func (x *ListUserReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *ListUserReq) sizeField1() (n int) {
	if x.PageNum == 0 {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetPageNum())
	return n
}

func (x *ListUserReq) sizeField2() (n int) {
	if x.PageSize == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetPageSize())
	return n
}

func (x *ListUserReq) sizeField3() (n int) {
	if x.UserName == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetUserName())
	return n
}

func (x *ListUserReq) sizeField4() (n int) {
	if x.Account == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetAccount())
	return n
}

func (x *ListUserResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *ListUserResp) sizeField1() (n int) {
	if x.UserList == nil {
		return n
	}
	for i := range x.GetUserList() {
		n += fastpb.SizeMessage(1, x.GetUserList()[i])
	}
	return n
}

func (x *ListUserResp) sizeField2() (n int) {
	if x.Total == 0 {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetTotal())
	return n
}

var fieldIDToName_LoginReq = map[int32]string{
	1: "UserAccount",
	2: "UserPassword",
}

var fieldIDToName_LoginResp = map[int32]string{
	1: "UserId",
	2: "UserRole",
}

var fieldIDToName_RegisterReq = map[int32]string{
	1: "UserAccount",
	2: "UserPassword",
}

var fieldIDToName_RegisterResp = map[int32]string{
	1: "UserId",
	2: "UserRole",
}

var fieldIDToName_UpdateReq = map[int32]string{
	1: "Id",
	2: "UserName",
	3: "UserAvatar",
	4: "UserProfile",
	5: "UserRole",
}

var fieldIDToName_UpdateResp = map[int32]string{}

var fieldIDToName_GetUserReq = map[int32]string{
	1: "Id",
}

var fieldIDToName_GetUserResp = map[int32]string{
	1:  "Id",
	2:  "UserAccount",
	3:  "UserPassword",
	4:  "UserName",
	5:  "UserAvatar",
	6:  "UserProfile",
	7:  "UserRole",
	8:  "EditTime",
	9:  "CreateTime",
	10: "UpdateTime",
	11: "IsDelete",
}

var fieldIDToName_DeleteUserReq = map[int32]string{
	1: "UserId",
}

var fieldIDToName_AddUserReq = map[int32]string{
	2: "UserAccount",
	3: "UserPassword",
	4: "UserName",
	5: "UserAvatar",
	6: "UserProfile",
	7: "UserRole",
}

var fieldIDToName_AddUserResp = map[int32]string{}

var fieldIDToName_DeleteUserResp = map[int32]string{}

var fieldIDToName_ListUserReq = map[int32]string{
	1: "PageNum",
	2: "PageSize",
	3: "UserName",
	4: "Account",
}

var fieldIDToName_ListUserResp = map[int32]string{
	1: "UserList",
	2: "Total",
}
