// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	user "github.com/MoScenix/wms/app/bff/biz/router/user"
	wms "github.com/MoScenix/wms/app/bff/biz/router/wms"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	wms.Register(r)
	user.Register(r)
}
