// Code generated by Kitex v0.9.1. DO NOT EDIT.

package wmsservice

import (
	"context"
	wms "github.com/MoScenix/wms/rpc_gen/kitex_gen/wms"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddWarehouse(ctx context.Context, Req *wms.AddWarehouseReq, callOptions ...callopt.Option) (r *wms.AddWarehouseResp, err error)
	UpdateWarehouse(ctx context.Context, Req *wms.UpdateWarehouseReq, callOptions ...callopt.Option) (r *wms.UpdateWarehouseResp, err error)
	GetWarehouse(ctx context.Context, Req *wms.GetWarehouseReq, callOptions ...callopt.Option) (r *wms.GetWarehouseResp, err error)
	ListWarehouse(ctx context.Context, Req *wms.ListWarehouseReq, callOptions ...callopt.Option) (r *wms.ListWarehouseResp, err error)
	AddLocation(ctx context.Context, Req *wms.AddLocationReq, callOptions ...callopt.Option) (r *wms.AddLocationResp, err error)
	UpdateLocation(ctx context.Context, Req *wms.UpdateLocationReq, callOptions ...callopt.Option) (r *wms.UpdateLocationResp, err error)
	GetLocation(ctx context.Context, Req *wms.GetLocationReq, callOptions ...callopt.Option) (r *wms.GetLocationResp, err error)
	ListLocation(ctx context.Context, Req *wms.ListLocationReq, callOptions ...callopt.Option) (r *wms.ListLocationResp, err error)
	AddSku(ctx context.Context, Req *wms.AddSkuReq, callOptions ...callopt.Option) (r *wms.AddSkuResp, err error)
	UpdateSku(ctx context.Context, Req *wms.UpdateSkuReq, callOptions ...callopt.Option) (r *wms.UpdateSkuResp, err error)
	GetSku(ctx context.Context, Req *wms.GetSkuReq, callOptions ...callopt.Option) (r *wms.GetSkuResp, err error)
	ListSku(ctx context.Context, Req *wms.ListSkuReq, callOptions ...callopt.Option) (r *wms.ListSkuResp, err error)
	GetInventory(ctx context.Context, Req *wms.GetInventoryReq, callOptions ...callopt.Option) (r *wms.GetInventoryResp, err error)
	ListInventory(ctx context.Context, Req *wms.ListInventoryReq, callOptions ...callopt.Option) (r *wms.ListInventoryResp, err error)
	CheckInventory(ctx context.Context, Req *wms.CheckInventoryReq, callOptions ...callopt.Option) (r *wms.CheckInventoryResp, err error)
	CreateInboundOrder(ctx context.Context, Req *wms.CreateInboundOrderReq, callOptions ...callopt.Option) (r *wms.CreateInboundOrderResp, err error)
	ReceiveInboundOrder(ctx context.Context, Req *wms.ReceiveInboundOrderReq, callOptions ...callopt.Option) (r *wms.ReceiveInboundOrderResp, err error)
	GetInboundOrder(ctx context.Context, Req *wms.GetInboundOrderReq, callOptions ...callopt.Option) (r *wms.GetInboundOrderResp, err error)
	ListInboundOrder(ctx context.Context, Req *wms.ListInboundOrderReq, callOptions ...callopt.Option) (r *wms.ListInboundOrderResp, err error)
	CreateOutboundOrder(ctx context.Context, Req *wms.CreateOutboundOrderReq, callOptions ...callopt.Option) (r *wms.CreateOutboundOrderResp, err error)
	ShipOutboundOrder(ctx context.Context, Req *wms.ShipOutboundOrderReq, callOptions ...callopt.Option) (r *wms.ShipOutboundOrderResp, err error)
	GetOutboundOrder(ctx context.Context, Req *wms.GetOutboundOrderReq, callOptions ...callopt.Option) (r *wms.GetOutboundOrderResp, err error)
	ListOutboundOrder(ctx context.Context, Req *wms.ListOutboundOrderReq, callOptions ...callopt.Option) (r *wms.ListOutboundOrderResp, err error)
	ListInventoryTxn(ctx context.Context, Req *wms.ListInventoryTxnReq, callOptions ...callopt.Option) (r *wms.ListInventoryTxnResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kWmsServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kWmsServiceClient struct {
	*kClient
}

func (p *kWmsServiceClient) AddWarehouse(ctx context.Context, Req *wms.AddWarehouseReq, callOptions ...callopt.Option) (r *wms.AddWarehouseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddWarehouse(ctx, Req)
}

func (p *kWmsServiceClient) UpdateWarehouse(ctx context.Context, Req *wms.UpdateWarehouseReq, callOptions ...callopt.Option) (r *wms.UpdateWarehouseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateWarehouse(ctx, Req)
}

func (p *kWmsServiceClient) GetWarehouse(ctx context.Context, Req *wms.GetWarehouseReq, callOptions ...callopt.Option) (r *wms.GetWarehouseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetWarehouse(ctx, Req)
}

func (p *kWmsServiceClient) ListWarehouse(ctx context.Context, Req *wms.ListWarehouseReq, callOptions ...callopt.Option) (r *wms.ListWarehouseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListWarehouse(ctx, Req)
}

func (p *kWmsServiceClient) AddLocation(ctx context.Context, Req *wms.AddLocationReq, callOptions ...callopt.Option) (r *wms.AddLocationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddLocation(ctx, Req)
}

func (p *kWmsServiceClient) UpdateLocation(ctx context.Context, Req *wms.UpdateLocationReq, callOptions ...callopt.Option) (r *wms.UpdateLocationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateLocation(ctx, Req)
}

func (p *kWmsServiceClient) GetLocation(ctx context.Context, Req *wms.GetLocationReq, callOptions ...callopt.Option) (r *wms.GetLocationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLocation(ctx, Req)
}

func (p *kWmsServiceClient) ListLocation(ctx context.Context, Req *wms.ListLocationReq, callOptions ...callopt.Option) (r *wms.ListLocationResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListLocation(ctx, Req)
}

func (p *kWmsServiceClient) AddSku(ctx context.Context, Req *wms.AddSkuReq, callOptions ...callopt.Option) (r *wms.AddSkuResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddSku(ctx, Req)
}

func (p *kWmsServiceClient) UpdateSku(ctx context.Context, Req *wms.UpdateSkuReq, callOptions ...callopt.Option) (r *wms.UpdateSkuResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateSku(ctx, Req)
}

func (p *kWmsServiceClient) GetSku(ctx context.Context, Req *wms.GetSkuReq, callOptions ...callopt.Option) (r *wms.GetSkuResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSku(ctx, Req)
}

func (p *kWmsServiceClient) ListSku(ctx context.Context, Req *wms.ListSkuReq, callOptions ...callopt.Option) (r *wms.ListSkuResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSku(ctx, Req)
}

func (p *kWmsServiceClient) GetInventory(ctx context.Context, Req *wms.GetInventoryReq, callOptions ...callopt.Option) (r *wms.GetInventoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetInventory(ctx, Req)
}

func (p *kWmsServiceClient) ListInventory(ctx context.Context, Req *wms.ListInventoryReq, callOptions ...callopt.Option) (r *wms.ListInventoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListInventory(ctx, Req)
}

func (p *kWmsServiceClient) CheckInventory(ctx context.Context, Req *wms.CheckInventoryReq, callOptions ...callopt.Option) (r *wms.CheckInventoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckInventory(ctx, Req)
}

func (p *kWmsServiceClient) CreateInboundOrder(ctx context.Context, Req *wms.CreateInboundOrderReq, callOptions ...callopt.Option) (r *wms.CreateInboundOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateInboundOrder(ctx, Req)
}

func (p *kWmsServiceClient) ReceiveInboundOrder(ctx context.Context, Req *wms.ReceiveInboundOrderReq, callOptions ...callopt.Option) (r *wms.ReceiveInboundOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReceiveInboundOrder(ctx, Req)
}

func (p *kWmsServiceClient) GetInboundOrder(ctx context.Context, Req *wms.GetInboundOrderReq, callOptions ...callopt.Option) (r *wms.GetInboundOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetInboundOrder(ctx, Req)
}

func (p *kWmsServiceClient) ListInboundOrder(ctx context.Context, Req *wms.ListInboundOrderReq, callOptions ...callopt.Option) (r *wms.ListInboundOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListInboundOrder(ctx, Req)
}

func (p *kWmsServiceClient) CreateOutboundOrder(ctx context.Context, Req *wms.CreateOutboundOrderReq, callOptions ...callopt.Option) (r *wms.CreateOutboundOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOutboundOrder(ctx, Req)
}

func (p *kWmsServiceClient) ShipOutboundOrder(ctx context.Context, Req *wms.ShipOutboundOrderReq, callOptions ...callopt.Option) (r *wms.ShipOutboundOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ShipOutboundOrder(ctx, Req)
}

func (p *kWmsServiceClient) GetOutboundOrder(ctx context.Context, Req *wms.GetOutboundOrderReq, callOptions ...callopt.Option) (r *wms.GetOutboundOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOutboundOrder(ctx, Req)
}

func (p *kWmsServiceClient) ListOutboundOrder(ctx context.Context, Req *wms.ListOutboundOrderReq, callOptions ...callopt.Option) (r *wms.ListOutboundOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOutboundOrder(ctx, Req)
}

func (p *kWmsServiceClient) ListInventoryTxn(ctx context.Context, Req *wms.ListInventoryTxnReq, callOptions ...callopt.Option) (r *wms.ListInventoryTxnResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListInventoryTxn(ctx, Req)
}
