// Code generated by Kitex v0.9.1. DO NOT EDIT.

package wmsservice

import (
	"context"
	"errors"
	wms "github.com/MoScenix/wms/rpc_gen/kitex_gen/wms"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AddWarehouse": kitex.NewMethodInfo(
		addWarehouseHandler,
		newAddWarehouseArgs,
		newAddWarehouseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateWarehouse": kitex.NewMethodInfo(
		updateWarehouseHandler,
		newUpdateWarehouseArgs,
		newUpdateWarehouseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetWarehouse": kitex.NewMethodInfo(
		getWarehouseHandler,
		newGetWarehouseArgs,
		newGetWarehouseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListWarehouse": kitex.NewMethodInfo(
		listWarehouseHandler,
		newListWarehouseArgs,
		newListWarehouseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddLocation": kitex.NewMethodInfo(
		addLocationHandler,
		newAddLocationArgs,
		newAddLocationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateLocation": kitex.NewMethodInfo(
		updateLocationHandler,
		newUpdateLocationArgs,
		newUpdateLocationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetLocation": kitex.NewMethodInfo(
		getLocationHandler,
		newGetLocationArgs,
		newGetLocationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListLocation": kitex.NewMethodInfo(
		listLocationHandler,
		newListLocationArgs,
		newListLocationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddSku": kitex.NewMethodInfo(
		addSkuHandler,
		newAddSkuArgs,
		newAddSkuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateSku": kitex.NewMethodInfo(
		updateSkuHandler,
		newUpdateSkuArgs,
		newUpdateSkuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetSku": kitex.NewMethodInfo(
		getSkuHandler,
		newGetSkuArgs,
		newGetSkuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListSku": kitex.NewMethodInfo(
		listSkuHandler,
		newListSkuArgs,
		newListSkuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetInventory": kitex.NewMethodInfo(
		getInventoryHandler,
		newGetInventoryArgs,
		newGetInventoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListInventory": kitex.NewMethodInfo(
		listInventoryHandler,
		newListInventoryArgs,
		newListInventoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CheckInventory": kitex.NewMethodInfo(
		checkInventoryHandler,
		newCheckInventoryArgs,
		newCheckInventoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateInboundOrder": kitex.NewMethodInfo(
		createInboundOrderHandler,
		newCreateInboundOrderArgs,
		newCreateInboundOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ReceiveInboundOrder": kitex.NewMethodInfo(
		receiveInboundOrderHandler,
		newReceiveInboundOrderArgs,
		newReceiveInboundOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetInboundOrder": kitex.NewMethodInfo(
		getInboundOrderHandler,
		newGetInboundOrderArgs,
		newGetInboundOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListInboundOrder": kitex.NewMethodInfo(
		listInboundOrderHandler,
		newListInboundOrderArgs,
		newListInboundOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateOutboundOrder": kitex.NewMethodInfo(
		createOutboundOrderHandler,
		newCreateOutboundOrderArgs,
		newCreateOutboundOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ShipOutboundOrder": kitex.NewMethodInfo(
		shipOutboundOrderHandler,
		newShipOutboundOrderArgs,
		newShipOutboundOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetOutboundOrder": kitex.NewMethodInfo(
		getOutboundOrderHandler,
		newGetOutboundOrderArgs,
		newGetOutboundOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListOutboundOrder": kitex.NewMethodInfo(
		listOutboundOrderHandler,
		newListOutboundOrderArgs,
		newListOutboundOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListInventoryTxn": kitex.NewMethodInfo(
		listInventoryTxnHandler,
		newListInventoryTxnArgs,
		newListInventoryTxnResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	wmsServiceServiceInfo                = NewServiceInfo()
	wmsServiceServiceInfoForClient       = NewServiceInfoForClient()
	wmsServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return wmsServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return wmsServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return wmsServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "WmsService"
	handlerType := (*wms.WmsService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "wms",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func addWarehouseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.AddWarehouseReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).AddWarehouse(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddWarehouseArgs:
		success, err := handler.(wms.WmsService).AddWarehouse(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddWarehouseResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddWarehouseArgs() interface{} {
	return &AddWarehouseArgs{}
}

func newAddWarehouseResult() interface{} {
	return &AddWarehouseResult{}
}

type AddWarehouseArgs struct {
	Req *wms.AddWarehouseReq
}

func (p *AddWarehouseArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.AddWarehouseReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddWarehouseArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddWarehouseArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddWarehouseArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddWarehouseArgs) Unmarshal(in []byte) error {
	msg := new(wms.AddWarehouseReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddWarehouseArgs_Req_DEFAULT *wms.AddWarehouseReq

func (p *AddWarehouseArgs) GetReq() *wms.AddWarehouseReq {
	if !p.IsSetReq() {
		return AddWarehouseArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddWarehouseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddWarehouseArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddWarehouseResult struct {
	Success *wms.AddWarehouseResp
}

var AddWarehouseResult_Success_DEFAULT *wms.AddWarehouseResp

func (p *AddWarehouseResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.AddWarehouseResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddWarehouseResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddWarehouseResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddWarehouseResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddWarehouseResult) Unmarshal(in []byte) error {
	msg := new(wms.AddWarehouseResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddWarehouseResult) GetSuccess() *wms.AddWarehouseResp {
	if !p.IsSetSuccess() {
		return AddWarehouseResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddWarehouseResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.AddWarehouseResp)
}

func (p *AddWarehouseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddWarehouseResult) GetResult() interface{} {
	return p.Success
}

func updateWarehouseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.UpdateWarehouseReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).UpdateWarehouse(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateWarehouseArgs:
		success, err := handler.(wms.WmsService).UpdateWarehouse(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateWarehouseResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateWarehouseArgs() interface{} {
	return &UpdateWarehouseArgs{}
}

func newUpdateWarehouseResult() interface{} {
	return &UpdateWarehouseResult{}
}

type UpdateWarehouseArgs struct {
	Req *wms.UpdateWarehouseReq
}

func (p *UpdateWarehouseArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.UpdateWarehouseReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateWarehouseArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateWarehouseArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateWarehouseArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateWarehouseArgs) Unmarshal(in []byte) error {
	msg := new(wms.UpdateWarehouseReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateWarehouseArgs_Req_DEFAULT *wms.UpdateWarehouseReq

func (p *UpdateWarehouseArgs) GetReq() *wms.UpdateWarehouseReq {
	if !p.IsSetReq() {
		return UpdateWarehouseArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateWarehouseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateWarehouseArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateWarehouseResult struct {
	Success *wms.UpdateWarehouseResp
}

var UpdateWarehouseResult_Success_DEFAULT *wms.UpdateWarehouseResp

func (p *UpdateWarehouseResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.UpdateWarehouseResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateWarehouseResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateWarehouseResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateWarehouseResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateWarehouseResult) Unmarshal(in []byte) error {
	msg := new(wms.UpdateWarehouseResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateWarehouseResult) GetSuccess() *wms.UpdateWarehouseResp {
	if !p.IsSetSuccess() {
		return UpdateWarehouseResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateWarehouseResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.UpdateWarehouseResp)
}

func (p *UpdateWarehouseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateWarehouseResult) GetResult() interface{} {
	return p.Success
}

func getWarehouseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.GetWarehouseReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).GetWarehouse(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetWarehouseArgs:
		success, err := handler.(wms.WmsService).GetWarehouse(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetWarehouseResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetWarehouseArgs() interface{} {
	return &GetWarehouseArgs{}
}

func newGetWarehouseResult() interface{} {
	return &GetWarehouseResult{}
}

type GetWarehouseArgs struct {
	Req *wms.GetWarehouseReq
}

func (p *GetWarehouseArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.GetWarehouseReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetWarehouseArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetWarehouseArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetWarehouseArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetWarehouseArgs) Unmarshal(in []byte) error {
	msg := new(wms.GetWarehouseReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetWarehouseArgs_Req_DEFAULT *wms.GetWarehouseReq

func (p *GetWarehouseArgs) GetReq() *wms.GetWarehouseReq {
	if !p.IsSetReq() {
		return GetWarehouseArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetWarehouseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetWarehouseArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetWarehouseResult struct {
	Success *wms.GetWarehouseResp
}

var GetWarehouseResult_Success_DEFAULT *wms.GetWarehouseResp

func (p *GetWarehouseResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.GetWarehouseResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetWarehouseResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetWarehouseResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetWarehouseResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetWarehouseResult) Unmarshal(in []byte) error {
	msg := new(wms.GetWarehouseResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetWarehouseResult) GetSuccess() *wms.GetWarehouseResp {
	if !p.IsSetSuccess() {
		return GetWarehouseResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetWarehouseResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.GetWarehouseResp)
}

func (p *GetWarehouseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetWarehouseResult) GetResult() interface{} {
	return p.Success
}

func listWarehouseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.ListWarehouseReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).ListWarehouse(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListWarehouseArgs:
		success, err := handler.(wms.WmsService).ListWarehouse(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListWarehouseResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListWarehouseArgs() interface{} {
	return &ListWarehouseArgs{}
}

func newListWarehouseResult() interface{} {
	return &ListWarehouseResult{}
}

type ListWarehouseArgs struct {
	Req *wms.ListWarehouseReq
}

func (p *ListWarehouseArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.ListWarehouseReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListWarehouseArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListWarehouseArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListWarehouseArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListWarehouseArgs) Unmarshal(in []byte) error {
	msg := new(wms.ListWarehouseReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListWarehouseArgs_Req_DEFAULT *wms.ListWarehouseReq

func (p *ListWarehouseArgs) GetReq() *wms.ListWarehouseReq {
	if !p.IsSetReq() {
		return ListWarehouseArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListWarehouseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListWarehouseArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListWarehouseResult struct {
	Success *wms.ListWarehouseResp
}

var ListWarehouseResult_Success_DEFAULT *wms.ListWarehouseResp

func (p *ListWarehouseResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.ListWarehouseResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListWarehouseResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListWarehouseResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListWarehouseResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListWarehouseResult) Unmarshal(in []byte) error {
	msg := new(wms.ListWarehouseResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListWarehouseResult) GetSuccess() *wms.ListWarehouseResp {
	if !p.IsSetSuccess() {
		return ListWarehouseResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListWarehouseResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.ListWarehouseResp)
}

func (p *ListWarehouseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListWarehouseResult) GetResult() interface{} {
	return p.Success
}

func addLocationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.AddLocationReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).AddLocation(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddLocationArgs:
		success, err := handler.(wms.WmsService).AddLocation(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddLocationResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddLocationArgs() interface{} {
	return &AddLocationArgs{}
}

func newAddLocationResult() interface{} {
	return &AddLocationResult{}
}

type AddLocationArgs struct {
	Req *wms.AddLocationReq
}

func (p *AddLocationArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.AddLocationReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddLocationArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddLocationArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddLocationArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddLocationArgs) Unmarshal(in []byte) error {
	msg := new(wms.AddLocationReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddLocationArgs_Req_DEFAULT *wms.AddLocationReq

func (p *AddLocationArgs) GetReq() *wms.AddLocationReq {
	if !p.IsSetReq() {
		return AddLocationArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddLocationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddLocationArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddLocationResult struct {
	Success *wms.AddLocationResp
}

var AddLocationResult_Success_DEFAULT *wms.AddLocationResp

func (p *AddLocationResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.AddLocationResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddLocationResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddLocationResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddLocationResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddLocationResult) Unmarshal(in []byte) error {
	msg := new(wms.AddLocationResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddLocationResult) GetSuccess() *wms.AddLocationResp {
	if !p.IsSetSuccess() {
		return AddLocationResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddLocationResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.AddLocationResp)
}

func (p *AddLocationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddLocationResult) GetResult() interface{} {
	return p.Success
}

func updateLocationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.UpdateLocationReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).UpdateLocation(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateLocationArgs:
		success, err := handler.(wms.WmsService).UpdateLocation(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateLocationResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateLocationArgs() interface{} {
	return &UpdateLocationArgs{}
}

func newUpdateLocationResult() interface{} {
	return &UpdateLocationResult{}
}

type UpdateLocationArgs struct {
	Req *wms.UpdateLocationReq
}

func (p *UpdateLocationArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.UpdateLocationReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateLocationArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateLocationArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateLocationArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateLocationArgs) Unmarshal(in []byte) error {
	msg := new(wms.UpdateLocationReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateLocationArgs_Req_DEFAULT *wms.UpdateLocationReq

func (p *UpdateLocationArgs) GetReq() *wms.UpdateLocationReq {
	if !p.IsSetReq() {
		return UpdateLocationArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateLocationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateLocationArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateLocationResult struct {
	Success *wms.UpdateLocationResp
}

var UpdateLocationResult_Success_DEFAULT *wms.UpdateLocationResp

func (p *UpdateLocationResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.UpdateLocationResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateLocationResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateLocationResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateLocationResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateLocationResult) Unmarshal(in []byte) error {
	msg := new(wms.UpdateLocationResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateLocationResult) GetSuccess() *wms.UpdateLocationResp {
	if !p.IsSetSuccess() {
		return UpdateLocationResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateLocationResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.UpdateLocationResp)
}

func (p *UpdateLocationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateLocationResult) GetResult() interface{} {
	return p.Success
}

func getLocationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.GetLocationReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).GetLocation(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetLocationArgs:
		success, err := handler.(wms.WmsService).GetLocation(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetLocationResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetLocationArgs() interface{} {
	return &GetLocationArgs{}
}

func newGetLocationResult() interface{} {
	return &GetLocationResult{}
}

type GetLocationArgs struct {
	Req *wms.GetLocationReq
}

func (p *GetLocationArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.GetLocationReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetLocationArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetLocationArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetLocationArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetLocationArgs) Unmarshal(in []byte) error {
	msg := new(wms.GetLocationReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetLocationArgs_Req_DEFAULT *wms.GetLocationReq

func (p *GetLocationArgs) GetReq() *wms.GetLocationReq {
	if !p.IsSetReq() {
		return GetLocationArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetLocationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetLocationArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetLocationResult struct {
	Success *wms.GetLocationResp
}

var GetLocationResult_Success_DEFAULT *wms.GetLocationResp

func (p *GetLocationResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.GetLocationResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetLocationResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetLocationResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetLocationResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetLocationResult) Unmarshal(in []byte) error {
	msg := new(wms.GetLocationResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetLocationResult) GetSuccess() *wms.GetLocationResp {
	if !p.IsSetSuccess() {
		return GetLocationResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetLocationResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.GetLocationResp)
}

func (p *GetLocationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetLocationResult) GetResult() interface{} {
	return p.Success
}

func listLocationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.ListLocationReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).ListLocation(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListLocationArgs:
		success, err := handler.(wms.WmsService).ListLocation(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListLocationResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListLocationArgs() interface{} {
	return &ListLocationArgs{}
}

func newListLocationResult() interface{} {
	return &ListLocationResult{}
}

type ListLocationArgs struct {
	Req *wms.ListLocationReq
}

func (p *ListLocationArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.ListLocationReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListLocationArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListLocationArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListLocationArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListLocationArgs) Unmarshal(in []byte) error {
	msg := new(wms.ListLocationReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListLocationArgs_Req_DEFAULT *wms.ListLocationReq

func (p *ListLocationArgs) GetReq() *wms.ListLocationReq {
	if !p.IsSetReq() {
		return ListLocationArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListLocationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListLocationArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListLocationResult struct {
	Success *wms.ListLocationResp
}

var ListLocationResult_Success_DEFAULT *wms.ListLocationResp

func (p *ListLocationResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.ListLocationResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListLocationResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListLocationResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListLocationResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListLocationResult) Unmarshal(in []byte) error {
	msg := new(wms.ListLocationResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListLocationResult) GetSuccess() *wms.ListLocationResp {
	if !p.IsSetSuccess() {
		return ListLocationResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListLocationResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.ListLocationResp)
}

func (p *ListLocationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListLocationResult) GetResult() interface{} {
	return p.Success
}

func addSkuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.AddSkuReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).AddSku(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddSkuArgs:
		success, err := handler.(wms.WmsService).AddSku(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddSkuResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddSkuArgs() interface{} {
	return &AddSkuArgs{}
}

func newAddSkuResult() interface{} {
	return &AddSkuResult{}
}

type AddSkuArgs struct {
	Req *wms.AddSkuReq
}

func (p *AddSkuArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.AddSkuReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AddSkuArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AddSkuArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AddSkuArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddSkuArgs) Unmarshal(in []byte) error {
	msg := new(wms.AddSkuReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddSkuArgs_Req_DEFAULT *wms.AddSkuReq

func (p *AddSkuArgs) GetReq() *wms.AddSkuReq {
	if !p.IsSetReq() {
		return AddSkuArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddSkuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddSkuArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddSkuResult struct {
	Success *wms.AddSkuResp
}

var AddSkuResult_Success_DEFAULT *wms.AddSkuResp

func (p *AddSkuResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.AddSkuResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AddSkuResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AddSkuResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AddSkuResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddSkuResult) Unmarshal(in []byte) error {
	msg := new(wms.AddSkuResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddSkuResult) GetSuccess() *wms.AddSkuResp {
	if !p.IsSetSuccess() {
		return AddSkuResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddSkuResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.AddSkuResp)
}

func (p *AddSkuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddSkuResult) GetResult() interface{} {
	return p.Success
}

func updateSkuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.UpdateSkuReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).UpdateSku(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateSkuArgs:
		success, err := handler.(wms.WmsService).UpdateSku(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateSkuResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateSkuArgs() interface{} {
	return &UpdateSkuArgs{}
}

func newUpdateSkuResult() interface{} {
	return &UpdateSkuResult{}
}

type UpdateSkuArgs struct {
	Req *wms.UpdateSkuReq
}

func (p *UpdateSkuArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.UpdateSkuReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateSkuArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateSkuArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateSkuArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateSkuArgs) Unmarshal(in []byte) error {
	msg := new(wms.UpdateSkuReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateSkuArgs_Req_DEFAULT *wms.UpdateSkuReq

func (p *UpdateSkuArgs) GetReq() *wms.UpdateSkuReq {
	if !p.IsSetReq() {
		return UpdateSkuArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateSkuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateSkuArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateSkuResult struct {
	Success *wms.UpdateSkuResp
}

var UpdateSkuResult_Success_DEFAULT *wms.UpdateSkuResp

func (p *UpdateSkuResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.UpdateSkuResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateSkuResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateSkuResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateSkuResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateSkuResult) Unmarshal(in []byte) error {
	msg := new(wms.UpdateSkuResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateSkuResult) GetSuccess() *wms.UpdateSkuResp {
	if !p.IsSetSuccess() {
		return UpdateSkuResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateSkuResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.UpdateSkuResp)
}

func (p *UpdateSkuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateSkuResult) GetResult() interface{} {
	return p.Success
}

func getSkuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.GetSkuReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).GetSku(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetSkuArgs:
		success, err := handler.(wms.WmsService).GetSku(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetSkuResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetSkuArgs() interface{} {
	return &GetSkuArgs{}
}

func newGetSkuResult() interface{} {
	return &GetSkuResult{}
}

type GetSkuArgs struct {
	Req *wms.GetSkuReq
}

func (p *GetSkuArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.GetSkuReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetSkuArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetSkuArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetSkuArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetSkuArgs) Unmarshal(in []byte) error {
	msg := new(wms.GetSkuReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetSkuArgs_Req_DEFAULT *wms.GetSkuReq

func (p *GetSkuArgs) GetReq() *wms.GetSkuReq {
	if !p.IsSetReq() {
		return GetSkuArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetSkuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetSkuArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetSkuResult struct {
	Success *wms.GetSkuResp
}

var GetSkuResult_Success_DEFAULT *wms.GetSkuResp

func (p *GetSkuResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.GetSkuResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetSkuResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetSkuResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetSkuResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetSkuResult) Unmarshal(in []byte) error {
	msg := new(wms.GetSkuResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetSkuResult) GetSuccess() *wms.GetSkuResp {
	if !p.IsSetSuccess() {
		return GetSkuResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetSkuResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.GetSkuResp)
}

func (p *GetSkuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetSkuResult) GetResult() interface{} {
	return p.Success
}

func listSkuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.ListSkuReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).ListSku(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListSkuArgs:
		success, err := handler.(wms.WmsService).ListSku(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListSkuResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListSkuArgs() interface{} {
	return &ListSkuArgs{}
}

func newListSkuResult() interface{} {
	return &ListSkuResult{}
}

type ListSkuArgs struct {
	Req *wms.ListSkuReq
}

func (p *ListSkuArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.ListSkuReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListSkuArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListSkuArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListSkuArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListSkuArgs) Unmarshal(in []byte) error {
	msg := new(wms.ListSkuReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListSkuArgs_Req_DEFAULT *wms.ListSkuReq

func (p *ListSkuArgs) GetReq() *wms.ListSkuReq {
	if !p.IsSetReq() {
		return ListSkuArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListSkuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListSkuArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListSkuResult struct {
	Success *wms.ListSkuResp
}

var ListSkuResult_Success_DEFAULT *wms.ListSkuResp

func (p *ListSkuResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.ListSkuResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListSkuResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListSkuResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListSkuResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListSkuResult) Unmarshal(in []byte) error {
	msg := new(wms.ListSkuResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListSkuResult) GetSuccess() *wms.ListSkuResp {
	if !p.IsSetSuccess() {
		return ListSkuResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListSkuResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.ListSkuResp)
}

func (p *ListSkuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListSkuResult) GetResult() interface{} {
	return p.Success
}

func getInventoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.GetInventoryReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).GetInventory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetInventoryArgs:
		success, err := handler.(wms.WmsService).GetInventory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetInventoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetInventoryArgs() interface{} {
	return &GetInventoryArgs{}
}

func newGetInventoryResult() interface{} {
	return &GetInventoryResult{}
}

type GetInventoryArgs struct {
	Req *wms.GetInventoryReq
}

func (p *GetInventoryArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.GetInventoryReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetInventoryArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetInventoryArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetInventoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetInventoryArgs) Unmarshal(in []byte) error {
	msg := new(wms.GetInventoryReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetInventoryArgs_Req_DEFAULT *wms.GetInventoryReq

func (p *GetInventoryArgs) GetReq() *wms.GetInventoryReq {
	if !p.IsSetReq() {
		return GetInventoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetInventoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetInventoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetInventoryResult struct {
	Success *wms.GetInventoryResp
}

var GetInventoryResult_Success_DEFAULT *wms.GetInventoryResp

func (p *GetInventoryResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.GetInventoryResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetInventoryResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetInventoryResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetInventoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetInventoryResult) Unmarshal(in []byte) error {
	msg := new(wms.GetInventoryResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetInventoryResult) GetSuccess() *wms.GetInventoryResp {
	if !p.IsSetSuccess() {
		return GetInventoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetInventoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.GetInventoryResp)
}

func (p *GetInventoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetInventoryResult) GetResult() interface{} {
	return p.Success
}

func listInventoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.ListInventoryReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).ListInventory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListInventoryArgs:
		success, err := handler.(wms.WmsService).ListInventory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListInventoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListInventoryArgs() interface{} {
	return &ListInventoryArgs{}
}

func newListInventoryResult() interface{} {
	return &ListInventoryResult{}
}

type ListInventoryArgs struct {
	Req *wms.ListInventoryReq
}

func (p *ListInventoryArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.ListInventoryReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListInventoryArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListInventoryArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListInventoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListInventoryArgs) Unmarshal(in []byte) error {
	msg := new(wms.ListInventoryReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListInventoryArgs_Req_DEFAULT *wms.ListInventoryReq

func (p *ListInventoryArgs) GetReq() *wms.ListInventoryReq {
	if !p.IsSetReq() {
		return ListInventoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListInventoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListInventoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListInventoryResult struct {
	Success *wms.ListInventoryResp
}

var ListInventoryResult_Success_DEFAULT *wms.ListInventoryResp

func (p *ListInventoryResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.ListInventoryResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListInventoryResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListInventoryResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListInventoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListInventoryResult) Unmarshal(in []byte) error {
	msg := new(wms.ListInventoryResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListInventoryResult) GetSuccess() *wms.ListInventoryResp {
	if !p.IsSetSuccess() {
		return ListInventoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListInventoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.ListInventoryResp)
}

func (p *ListInventoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListInventoryResult) GetResult() interface{} {
	return p.Success
}

func checkInventoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.CheckInventoryReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).CheckInventory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CheckInventoryArgs:
		success, err := handler.(wms.WmsService).CheckInventory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CheckInventoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCheckInventoryArgs() interface{} {
	return &CheckInventoryArgs{}
}

func newCheckInventoryResult() interface{} {
	return &CheckInventoryResult{}
}

type CheckInventoryArgs struct {
	Req *wms.CheckInventoryReq
}

func (p *CheckInventoryArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.CheckInventoryReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CheckInventoryArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CheckInventoryArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CheckInventoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CheckInventoryArgs) Unmarshal(in []byte) error {
	msg := new(wms.CheckInventoryReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CheckInventoryArgs_Req_DEFAULT *wms.CheckInventoryReq

func (p *CheckInventoryArgs) GetReq() *wms.CheckInventoryReq {
	if !p.IsSetReq() {
		return CheckInventoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CheckInventoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CheckInventoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CheckInventoryResult struct {
	Success *wms.CheckInventoryResp
}

var CheckInventoryResult_Success_DEFAULT *wms.CheckInventoryResp

func (p *CheckInventoryResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.CheckInventoryResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CheckInventoryResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CheckInventoryResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CheckInventoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CheckInventoryResult) Unmarshal(in []byte) error {
	msg := new(wms.CheckInventoryResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CheckInventoryResult) GetSuccess() *wms.CheckInventoryResp {
	if !p.IsSetSuccess() {
		return CheckInventoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CheckInventoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.CheckInventoryResp)
}

func (p *CheckInventoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CheckInventoryResult) GetResult() interface{} {
	return p.Success
}

func createInboundOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.CreateInboundOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).CreateInboundOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateInboundOrderArgs:
		success, err := handler.(wms.WmsService).CreateInboundOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateInboundOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateInboundOrderArgs() interface{} {
	return &CreateInboundOrderArgs{}
}

func newCreateInboundOrderResult() interface{} {
	return &CreateInboundOrderResult{}
}

type CreateInboundOrderArgs struct {
	Req *wms.CreateInboundOrderReq
}

func (p *CreateInboundOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.CreateInboundOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CreateInboundOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CreateInboundOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CreateInboundOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateInboundOrderArgs) Unmarshal(in []byte) error {
	msg := new(wms.CreateInboundOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateInboundOrderArgs_Req_DEFAULT *wms.CreateInboundOrderReq

func (p *CreateInboundOrderArgs) GetReq() *wms.CreateInboundOrderReq {
	if !p.IsSetReq() {
		return CreateInboundOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateInboundOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateInboundOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateInboundOrderResult struct {
	Success *wms.CreateInboundOrderResp
}

var CreateInboundOrderResult_Success_DEFAULT *wms.CreateInboundOrderResp

func (p *CreateInboundOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.CreateInboundOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CreateInboundOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CreateInboundOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CreateInboundOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateInboundOrderResult) Unmarshal(in []byte) error {
	msg := new(wms.CreateInboundOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateInboundOrderResult) GetSuccess() *wms.CreateInboundOrderResp {
	if !p.IsSetSuccess() {
		return CreateInboundOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateInboundOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.CreateInboundOrderResp)
}

func (p *CreateInboundOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateInboundOrderResult) GetResult() interface{} {
	return p.Success
}

func receiveInboundOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.ReceiveInboundOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).ReceiveInboundOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ReceiveInboundOrderArgs:
		success, err := handler.(wms.WmsService).ReceiveInboundOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ReceiveInboundOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newReceiveInboundOrderArgs() interface{} {
	return &ReceiveInboundOrderArgs{}
}

func newReceiveInboundOrderResult() interface{} {
	return &ReceiveInboundOrderResult{}
}

type ReceiveInboundOrderArgs struct {
	Req *wms.ReceiveInboundOrderReq
}

func (p *ReceiveInboundOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.ReceiveInboundOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ReceiveInboundOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ReceiveInboundOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ReceiveInboundOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ReceiveInboundOrderArgs) Unmarshal(in []byte) error {
	msg := new(wms.ReceiveInboundOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ReceiveInboundOrderArgs_Req_DEFAULT *wms.ReceiveInboundOrderReq

func (p *ReceiveInboundOrderArgs) GetReq() *wms.ReceiveInboundOrderReq {
	if !p.IsSetReq() {
		return ReceiveInboundOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ReceiveInboundOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ReceiveInboundOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ReceiveInboundOrderResult struct {
	Success *wms.ReceiveInboundOrderResp
}

var ReceiveInboundOrderResult_Success_DEFAULT *wms.ReceiveInboundOrderResp

func (p *ReceiveInboundOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.ReceiveInboundOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ReceiveInboundOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ReceiveInboundOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ReceiveInboundOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ReceiveInboundOrderResult) Unmarshal(in []byte) error {
	msg := new(wms.ReceiveInboundOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ReceiveInboundOrderResult) GetSuccess() *wms.ReceiveInboundOrderResp {
	if !p.IsSetSuccess() {
		return ReceiveInboundOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ReceiveInboundOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.ReceiveInboundOrderResp)
}

func (p *ReceiveInboundOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ReceiveInboundOrderResult) GetResult() interface{} {
	return p.Success
}

func getInboundOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.GetInboundOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).GetInboundOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetInboundOrderArgs:
		success, err := handler.(wms.WmsService).GetInboundOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetInboundOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetInboundOrderArgs() interface{} {
	return &GetInboundOrderArgs{}
}

func newGetInboundOrderResult() interface{} {
	return &GetInboundOrderResult{}
}

type GetInboundOrderArgs struct {
	Req *wms.GetInboundOrderReq
}

func (p *GetInboundOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.GetInboundOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetInboundOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetInboundOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetInboundOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetInboundOrderArgs) Unmarshal(in []byte) error {
	msg := new(wms.GetInboundOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetInboundOrderArgs_Req_DEFAULT *wms.GetInboundOrderReq

func (p *GetInboundOrderArgs) GetReq() *wms.GetInboundOrderReq {
	if !p.IsSetReq() {
		return GetInboundOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetInboundOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetInboundOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetInboundOrderResult struct {
	Success *wms.GetInboundOrderResp
}

var GetInboundOrderResult_Success_DEFAULT *wms.GetInboundOrderResp

func (p *GetInboundOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.GetInboundOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetInboundOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetInboundOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetInboundOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetInboundOrderResult) Unmarshal(in []byte) error {
	msg := new(wms.GetInboundOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetInboundOrderResult) GetSuccess() *wms.GetInboundOrderResp {
	if !p.IsSetSuccess() {
		return GetInboundOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetInboundOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.GetInboundOrderResp)
}

func (p *GetInboundOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetInboundOrderResult) GetResult() interface{} {
	return p.Success
}

func listInboundOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.ListInboundOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).ListInboundOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListInboundOrderArgs:
		success, err := handler.(wms.WmsService).ListInboundOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListInboundOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListInboundOrderArgs() interface{} {
	return &ListInboundOrderArgs{}
}

func newListInboundOrderResult() interface{} {
	return &ListInboundOrderResult{}
}

type ListInboundOrderArgs struct {
	Req *wms.ListInboundOrderReq
}

func (p *ListInboundOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.ListInboundOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListInboundOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListInboundOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListInboundOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListInboundOrderArgs) Unmarshal(in []byte) error {
	msg := new(wms.ListInboundOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListInboundOrderArgs_Req_DEFAULT *wms.ListInboundOrderReq

func (p *ListInboundOrderArgs) GetReq() *wms.ListInboundOrderReq {
	if !p.IsSetReq() {
		return ListInboundOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListInboundOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListInboundOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListInboundOrderResult struct {
	Success *wms.ListInboundOrderResp
}

var ListInboundOrderResult_Success_DEFAULT *wms.ListInboundOrderResp

func (p *ListInboundOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.ListInboundOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListInboundOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListInboundOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListInboundOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListInboundOrderResult) Unmarshal(in []byte) error {
	msg := new(wms.ListInboundOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListInboundOrderResult) GetSuccess() *wms.ListInboundOrderResp {
	if !p.IsSetSuccess() {
		return ListInboundOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListInboundOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.ListInboundOrderResp)
}

func (p *ListInboundOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListInboundOrderResult) GetResult() interface{} {
	return p.Success
}

func createOutboundOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.CreateOutboundOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).CreateOutboundOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateOutboundOrderArgs:
		success, err := handler.(wms.WmsService).CreateOutboundOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateOutboundOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateOutboundOrderArgs() interface{} {
	return &CreateOutboundOrderArgs{}
}

func newCreateOutboundOrderResult() interface{} {
	return &CreateOutboundOrderResult{}
}

type CreateOutboundOrderArgs struct {
	Req *wms.CreateOutboundOrderReq
}

func (p *CreateOutboundOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.CreateOutboundOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CreateOutboundOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CreateOutboundOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CreateOutboundOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateOutboundOrderArgs) Unmarshal(in []byte) error {
	msg := new(wms.CreateOutboundOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateOutboundOrderArgs_Req_DEFAULT *wms.CreateOutboundOrderReq

func (p *CreateOutboundOrderArgs) GetReq() *wms.CreateOutboundOrderReq {
	if !p.IsSetReq() {
		return CreateOutboundOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateOutboundOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateOutboundOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateOutboundOrderResult struct {
	Success *wms.CreateOutboundOrderResp
}

var CreateOutboundOrderResult_Success_DEFAULT *wms.CreateOutboundOrderResp

func (p *CreateOutboundOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.CreateOutboundOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CreateOutboundOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CreateOutboundOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CreateOutboundOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateOutboundOrderResult) Unmarshal(in []byte) error {
	msg := new(wms.CreateOutboundOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateOutboundOrderResult) GetSuccess() *wms.CreateOutboundOrderResp {
	if !p.IsSetSuccess() {
		return CreateOutboundOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateOutboundOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.CreateOutboundOrderResp)
}

func (p *CreateOutboundOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateOutboundOrderResult) GetResult() interface{} {
	return p.Success
}

func shipOutboundOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.ShipOutboundOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).ShipOutboundOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ShipOutboundOrderArgs:
		success, err := handler.(wms.WmsService).ShipOutboundOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ShipOutboundOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newShipOutboundOrderArgs() interface{} {
	return &ShipOutboundOrderArgs{}
}

func newShipOutboundOrderResult() interface{} {
	return &ShipOutboundOrderResult{}
}

type ShipOutboundOrderArgs struct {
	Req *wms.ShipOutboundOrderReq
}

func (p *ShipOutboundOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.ShipOutboundOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ShipOutboundOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ShipOutboundOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ShipOutboundOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ShipOutboundOrderArgs) Unmarshal(in []byte) error {
	msg := new(wms.ShipOutboundOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ShipOutboundOrderArgs_Req_DEFAULT *wms.ShipOutboundOrderReq

func (p *ShipOutboundOrderArgs) GetReq() *wms.ShipOutboundOrderReq {
	if !p.IsSetReq() {
		return ShipOutboundOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ShipOutboundOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ShipOutboundOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ShipOutboundOrderResult struct {
	Success *wms.ShipOutboundOrderResp
}

var ShipOutboundOrderResult_Success_DEFAULT *wms.ShipOutboundOrderResp

func (p *ShipOutboundOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.ShipOutboundOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ShipOutboundOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ShipOutboundOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ShipOutboundOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ShipOutboundOrderResult) Unmarshal(in []byte) error {
	msg := new(wms.ShipOutboundOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ShipOutboundOrderResult) GetSuccess() *wms.ShipOutboundOrderResp {
	if !p.IsSetSuccess() {
		return ShipOutboundOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ShipOutboundOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.ShipOutboundOrderResp)
}

func (p *ShipOutboundOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ShipOutboundOrderResult) GetResult() interface{} {
	return p.Success
}

func getOutboundOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.GetOutboundOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).GetOutboundOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetOutboundOrderArgs:
		success, err := handler.(wms.WmsService).GetOutboundOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetOutboundOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetOutboundOrderArgs() interface{} {
	return &GetOutboundOrderArgs{}
}

func newGetOutboundOrderResult() interface{} {
	return &GetOutboundOrderResult{}
}

type GetOutboundOrderArgs struct {
	Req *wms.GetOutboundOrderReq
}

func (p *GetOutboundOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.GetOutboundOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetOutboundOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetOutboundOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetOutboundOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetOutboundOrderArgs) Unmarshal(in []byte) error {
	msg := new(wms.GetOutboundOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetOutboundOrderArgs_Req_DEFAULT *wms.GetOutboundOrderReq

func (p *GetOutboundOrderArgs) GetReq() *wms.GetOutboundOrderReq {
	if !p.IsSetReq() {
		return GetOutboundOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetOutboundOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetOutboundOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetOutboundOrderResult struct {
	Success *wms.GetOutboundOrderResp
}

var GetOutboundOrderResult_Success_DEFAULT *wms.GetOutboundOrderResp

func (p *GetOutboundOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.GetOutboundOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetOutboundOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetOutboundOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetOutboundOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetOutboundOrderResult) Unmarshal(in []byte) error {
	msg := new(wms.GetOutboundOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetOutboundOrderResult) GetSuccess() *wms.GetOutboundOrderResp {
	if !p.IsSetSuccess() {
		return GetOutboundOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetOutboundOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.GetOutboundOrderResp)
}

func (p *GetOutboundOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetOutboundOrderResult) GetResult() interface{} {
	return p.Success
}

func listOutboundOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.ListOutboundOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).ListOutboundOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListOutboundOrderArgs:
		success, err := handler.(wms.WmsService).ListOutboundOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListOutboundOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListOutboundOrderArgs() interface{} {
	return &ListOutboundOrderArgs{}
}

func newListOutboundOrderResult() interface{} {
	return &ListOutboundOrderResult{}
}

type ListOutboundOrderArgs struct {
	Req *wms.ListOutboundOrderReq
}

func (p *ListOutboundOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.ListOutboundOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListOutboundOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListOutboundOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListOutboundOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListOutboundOrderArgs) Unmarshal(in []byte) error {
	msg := new(wms.ListOutboundOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListOutboundOrderArgs_Req_DEFAULT *wms.ListOutboundOrderReq

func (p *ListOutboundOrderArgs) GetReq() *wms.ListOutboundOrderReq {
	if !p.IsSetReq() {
		return ListOutboundOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListOutboundOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListOutboundOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListOutboundOrderResult struct {
	Success *wms.ListOutboundOrderResp
}

var ListOutboundOrderResult_Success_DEFAULT *wms.ListOutboundOrderResp

func (p *ListOutboundOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.ListOutboundOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListOutboundOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListOutboundOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListOutboundOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListOutboundOrderResult) Unmarshal(in []byte) error {
	msg := new(wms.ListOutboundOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListOutboundOrderResult) GetSuccess() *wms.ListOutboundOrderResp {
	if !p.IsSetSuccess() {
		return ListOutboundOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListOutboundOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.ListOutboundOrderResp)
}

func (p *ListOutboundOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListOutboundOrderResult) GetResult() interface{} {
	return p.Success
}

func listInventoryTxnHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(wms.ListInventoryTxnReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(wms.WmsService).ListInventoryTxn(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListInventoryTxnArgs:
		success, err := handler.(wms.WmsService).ListInventoryTxn(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListInventoryTxnResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListInventoryTxnArgs() interface{} {
	return &ListInventoryTxnArgs{}
}

func newListInventoryTxnResult() interface{} {
	return &ListInventoryTxnResult{}
}

type ListInventoryTxnArgs struct {
	Req *wms.ListInventoryTxnReq
}

func (p *ListInventoryTxnArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(wms.ListInventoryTxnReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListInventoryTxnArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListInventoryTxnArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListInventoryTxnArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListInventoryTxnArgs) Unmarshal(in []byte) error {
	msg := new(wms.ListInventoryTxnReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListInventoryTxnArgs_Req_DEFAULT *wms.ListInventoryTxnReq

func (p *ListInventoryTxnArgs) GetReq() *wms.ListInventoryTxnReq {
	if !p.IsSetReq() {
		return ListInventoryTxnArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListInventoryTxnArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListInventoryTxnArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListInventoryTxnResult struct {
	Success *wms.ListInventoryTxnResp
}

var ListInventoryTxnResult_Success_DEFAULT *wms.ListInventoryTxnResp

func (p *ListInventoryTxnResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(wms.ListInventoryTxnResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListInventoryTxnResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListInventoryTxnResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListInventoryTxnResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListInventoryTxnResult) Unmarshal(in []byte) error {
	msg := new(wms.ListInventoryTxnResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListInventoryTxnResult) GetSuccess() *wms.ListInventoryTxnResp {
	if !p.IsSetSuccess() {
		return ListInventoryTxnResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListInventoryTxnResult) SetSuccess(x interface{}) {
	p.Success = x.(*wms.ListInventoryTxnResp)
}

func (p *ListInventoryTxnResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListInventoryTxnResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddWarehouse(ctx context.Context, Req *wms.AddWarehouseReq) (r *wms.AddWarehouseResp, err error) {
	var _args AddWarehouseArgs
	_args.Req = Req
	var _result AddWarehouseResult
	if err = p.c.Call(ctx, "AddWarehouse", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateWarehouse(ctx context.Context, Req *wms.UpdateWarehouseReq) (r *wms.UpdateWarehouseResp, err error) {
	var _args UpdateWarehouseArgs
	_args.Req = Req
	var _result UpdateWarehouseResult
	if err = p.c.Call(ctx, "UpdateWarehouse", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetWarehouse(ctx context.Context, Req *wms.GetWarehouseReq) (r *wms.GetWarehouseResp, err error) {
	var _args GetWarehouseArgs
	_args.Req = Req
	var _result GetWarehouseResult
	if err = p.c.Call(ctx, "GetWarehouse", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListWarehouse(ctx context.Context, Req *wms.ListWarehouseReq) (r *wms.ListWarehouseResp, err error) {
	var _args ListWarehouseArgs
	_args.Req = Req
	var _result ListWarehouseResult
	if err = p.c.Call(ctx, "ListWarehouse", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddLocation(ctx context.Context, Req *wms.AddLocationReq) (r *wms.AddLocationResp, err error) {
	var _args AddLocationArgs
	_args.Req = Req
	var _result AddLocationResult
	if err = p.c.Call(ctx, "AddLocation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateLocation(ctx context.Context, Req *wms.UpdateLocationReq) (r *wms.UpdateLocationResp, err error) {
	var _args UpdateLocationArgs
	_args.Req = Req
	var _result UpdateLocationResult
	if err = p.c.Call(ctx, "UpdateLocation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLocation(ctx context.Context, Req *wms.GetLocationReq) (r *wms.GetLocationResp, err error) {
	var _args GetLocationArgs
	_args.Req = Req
	var _result GetLocationResult
	if err = p.c.Call(ctx, "GetLocation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListLocation(ctx context.Context, Req *wms.ListLocationReq) (r *wms.ListLocationResp, err error) {
	var _args ListLocationArgs
	_args.Req = Req
	var _result ListLocationResult
	if err = p.c.Call(ctx, "ListLocation", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddSku(ctx context.Context, Req *wms.AddSkuReq) (r *wms.AddSkuResp, err error) {
	var _args AddSkuArgs
	_args.Req = Req
	var _result AddSkuResult
	if err = p.c.Call(ctx, "AddSku", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateSku(ctx context.Context, Req *wms.UpdateSkuReq) (r *wms.UpdateSkuResp, err error) {
	var _args UpdateSkuArgs
	_args.Req = Req
	var _result UpdateSkuResult
	if err = p.c.Call(ctx, "UpdateSku", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSku(ctx context.Context, Req *wms.GetSkuReq) (r *wms.GetSkuResp, err error) {
	var _args GetSkuArgs
	_args.Req = Req
	var _result GetSkuResult
	if err = p.c.Call(ctx, "GetSku", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSku(ctx context.Context, Req *wms.ListSkuReq) (r *wms.ListSkuResp, err error) {
	var _args ListSkuArgs
	_args.Req = Req
	var _result ListSkuResult
	if err = p.c.Call(ctx, "ListSku", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetInventory(ctx context.Context, Req *wms.GetInventoryReq) (r *wms.GetInventoryResp, err error) {
	var _args GetInventoryArgs
	_args.Req = Req
	var _result GetInventoryResult
	if err = p.c.Call(ctx, "GetInventory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListInventory(ctx context.Context, Req *wms.ListInventoryReq) (r *wms.ListInventoryResp, err error) {
	var _args ListInventoryArgs
	_args.Req = Req
	var _result ListInventoryResult
	if err = p.c.Call(ctx, "ListInventory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckInventory(ctx context.Context, Req *wms.CheckInventoryReq) (r *wms.CheckInventoryResp, err error) {
	var _args CheckInventoryArgs
	_args.Req = Req
	var _result CheckInventoryResult
	if err = p.c.Call(ctx, "CheckInventory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateInboundOrder(ctx context.Context, Req *wms.CreateInboundOrderReq) (r *wms.CreateInboundOrderResp, err error) {
	var _args CreateInboundOrderArgs
	_args.Req = Req
	var _result CreateInboundOrderResult
	if err = p.c.Call(ctx, "CreateInboundOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReceiveInboundOrder(ctx context.Context, Req *wms.ReceiveInboundOrderReq) (r *wms.ReceiveInboundOrderResp, err error) {
	var _args ReceiveInboundOrderArgs
	_args.Req = Req
	var _result ReceiveInboundOrderResult
	if err = p.c.Call(ctx, "ReceiveInboundOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetInboundOrder(ctx context.Context, Req *wms.GetInboundOrderReq) (r *wms.GetInboundOrderResp, err error) {
	var _args GetInboundOrderArgs
	_args.Req = Req
	var _result GetInboundOrderResult
	if err = p.c.Call(ctx, "GetInboundOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListInboundOrder(ctx context.Context, Req *wms.ListInboundOrderReq) (r *wms.ListInboundOrderResp, err error) {
	var _args ListInboundOrderArgs
	_args.Req = Req
	var _result ListInboundOrderResult
	if err = p.c.Call(ctx, "ListInboundOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateOutboundOrder(ctx context.Context, Req *wms.CreateOutboundOrderReq) (r *wms.CreateOutboundOrderResp, err error) {
	var _args CreateOutboundOrderArgs
	_args.Req = Req
	var _result CreateOutboundOrderResult
	if err = p.c.Call(ctx, "CreateOutboundOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ShipOutboundOrder(ctx context.Context, Req *wms.ShipOutboundOrderReq) (r *wms.ShipOutboundOrderResp, err error) {
	var _args ShipOutboundOrderArgs
	_args.Req = Req
	var _result ShipOutboundOrderResult
	if err = p.c.Call(ctx, "ShipOutboundOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOutboundOrder(ctx context.Context, Req *wms.GetOutboundOrderReq) (r *wms.GetOutboundOrderResp, err error) {
	var _args GetOutboundOrderArgs
	_args.Req = Req
	var _result GetOutboundOrderResult
	if err = p.c.Call(ctx, "GetOutboundOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListOutboundOrder(ctx context.Context, Req *wms.ListOutboundOrderReq) (r *wms.ListOutboundOrderResp, err error) {
	var _args ListOutboundOrderArgs
	_args.Req = Req
	var _result ListOutboundOrderResult
	if err = p.c.Call(ctx, "ListOutboundOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListInventoryTxn(ctx context.Context, Req *wms.ListInventoryTxnReq) (r *wms.ListInventoryTxnResp, err error) {
	var _args ListInventoryTxnArgs
	_args.Req = Req
	var _result ListInventoryTxnResult
	if err = p.c.Call(ctx, "ListInventoryTxn", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
