// Code generated by hertz generator.

package wms

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wmsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _inboundMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createinboundorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinboundorderbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _receiveinboundorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listinboundorderbypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _inventoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkinventoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinventorybyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listinventorybypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _locationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addlocationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlocationbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatelocationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listlocationbypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _outboundMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createoutboundorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getoutboundorderbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shipoutboundorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listoutboundorderbypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _skuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addskuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getskubyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateskuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list3Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listskubypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _txnMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list4Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listinventorytxnbypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _warehouseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addwarehouseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getwarehousebyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatewarehouseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list5Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listwarehousebypageMw() []app.HandlerFunc {
	// your code...
	return nil
}
